// Central icon set — VS Code Codicons via react-icons, aliased to semantic names
// so the rest of the app imports from one place. Icons inherit `currentColor`;
// size with the `size` prop or a className.
export {
  VscChevronDown as ChevronDown,
  VscChevronUp as ChevronUp,
  VscChevronLeft as ChevronLeft,
  VscChevronRight as ChevronRight,
  VscLayoutSidebarLeft as Collapse,
  VscClose as Close,
  VscCheck as Check,
  VscAdd as Plus,
  VscTrash as Trash,
  VscEdit as Pen,
  VscEye as Eye,
  VscEyeClosed as EyeOff,
  VscDesktopDownload as Download,
  VscCloudUpload as Upload,
  VscFileMedia as ImageIcon,
  VscPlay as Play,
  VscKebabVertical as More,
  VscBookmark as Bookmark,
  VscFolder as Folder,
  VscCalendar as Calendar,
  VscLinkExternal as External,
  VscMusic as Music,
  VscFile as FileDoc,
  VscArrowLeft as ArrowLeft,
  VscArrowRight as ArrowRight,
  VscDebugPause as Pause,
  VscTriangleLeft as SkipBack,
  VscTriangleRight as SkipForward,
  VscSortPrecedence as Sort,
  VscGraphLine as Chart,
  VscComment as Comment,
  VscShield as Watermark,
  VscLayout as Grid,
  VscGear as Gear,
  VscListUnordered as ListIcon,
  VscLoading as SpinnerIcon,
  VscGrabber as Grip,
  VscHeart as HeartOpen,
  VscHeartFilled as Heart,
} from "react-icons/vsc";
