// Central icon set — css.gg via react-icons, aliased to semantic names so the
// rest of the app imports from one place. Icons inherit `currentColor`; size
// with a className (e.g. `className="h-4 w-4"`).
export {
  CgChevronDown as ChevronDown,
  CgChevronUp as ChevronUp,
  CgChevronLeft as ChevronLeft,
  CgChevronRight as ChevronRight,
  CgChevronDoubleLeft as Collapse,
  CgClose as Close,
  CgCheck as Check,
  CgMathPlus as Plus,
  CgTrash as Trash,
  CgPen as Pen,
  CgEye as Eye,
  CgEyeAlt as EyeOff,
  CgSoftwareDownload as Download,
  CgSoftwareUpload as Upload,
  CgImage as ImageIcon,
  CgPlayButtonO as Play,
  CgMoreVerticalAlt as More,
  CgBookmark as Bookmark,
  CgHeart as Heart,
  CgFolder as Folder,
  CgCalendar as Calendar,
  CgExternal as External,
  CgMusic as Music,
  CgFileDocument as FileDoc,
  CgArrowLeft as ArrowLeft,
  CgArrowRight as ArrowRight,
  CgSortAz as Sort,
  CgChart as Chart,
  CgComment as Comment,
  CgCopyright as Watermark,
  CgViewGrid as Grid,
  CgOptions as Gear,
  CgList as ListIcon,
  CgSpinner as SpinnerIcon,
} from 'react-icons/cg';
